export const UPDATE_SELECTED_LANGUAGE_KEY = 'UPDATE_SELECTED_LANGUAGE_KEY';
export const UPDATE_MULTILINGUAL_ROUTES = 'UPDATE_MULTILINGUAL_ROUTES';
export const UPDATE_HAS_ACCEPTED_POLICY = 'UPDATE_HAS_ACCEPTED_POLICY';
