export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const CREATE_RELEASE = 'CREATE_RELEASE';
export const UPDATE_RELEASES = 'UPDATE_RELEASES';
export const CREATE_VIDEO = 'CREATE_VIDEO';
export const UPDATE_VIDEOS = 'UPDATE_VIDEOS';
